spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionmedica_db
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update  # ← ahora los datos no se borrarán
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080

security:
  jwt:
    secret-key: clave-secreta-supersegura-123456
    expiration: 3600000  # 1 hora (en milisegundos)
